using System;
using System.Runtime.InteropServices;

using Fairweather.Service;

namespace Sage_Int
{
    partial class SIT_Engine
    {
        // ****************************
        /*       Static Mode         */
        // ****************************


        static readonly string[]
        record_static = { "ACCOUNT_REF", "NAME", "ADDRESS_1", "ADDRESS_2", "ADDRESS_3", "ADDRESS_4", "ADDRESS_5",
"CONTACT_NAME", "TELEPHONE", "FAX", "ANALYSIS_1", "ANALYSIS_2", "ANALYSIS_3", "DEPT_NUMBER", 
"VAT_REG_NUMBER", "TURNOVER_MTD", "TURNOVER_YTD", "PRIOR_YTD", "CREDIT_LIMIT", "TERMS", 
"SETTLEMENT_DUE_DAYS", "SETTLEMENT_DISC_RATE", "DEF_NOM_CODE", "DEF_TAX_CODE" };



        static readonly string[]
        nominal_static = { "NOMINAL_CODE", "NAME", 
"YEARLY_BUDGET"/*(TOTAL_OF_BUDGETS_MONTHS_1-12)*/, 
"BUDGET_MONTH_1", "BUDGET_MONTH_2", "BUDGET_MONTH_3", 
"BUDGET_MONTH_4", "BUDGET_MONTH_5", "BUDGET_MONTH_6", 
"BUDGET_MONTH_7", "BUDGET_MONTH_8", "BUDGET_MONTH_9", 
"BUDGET_MONTH_10", "BUDGET_MONTH_11", "BUDGET_MONTH_12" };



        static readonly string[]
        stock_static = { "STOCK_CODE", "DESCRIPTION", "TAX_CODE", "SALES_PRICE", "UNIT_OF_SALE", "LOCATION", "NOMINAL_CODE", "STOCK_CAT", 
"DEPT_NUMBER", "PURCHASE_REF", "SUPPLIER_PART_NUMBER", "QTY_REORDER_LEVEL" };




        static readonly string[]
        audit_static = { "TYPE", "ACCOUNT_REF", "NOMINAL_CODE", "DEPT_NUMBER", "DATE", "INV_REF", 
"DETAILS", "NET_AMOUNT", "TAX_CODE", "TAX_AMOUNT" };



        static readonly string[]
        stockTran_static = { "TYPE", "STOCK_CODE", "DATE", "REFERENCE", "DETAILS", "QUANTITY", "COST_PRICE", "SALES_PRICE" };



        // ****************************
        /*       Dynamic Mode        */
        // ****************************


        static string[] sales_headers = {  
#region data 
"ACCOUNT_MANAGER", "ACCOUNT_ON_HOLD", "ACCOUNT_OPENED", "ACCOUNT_REF", "ACCOUNT_STATUS", "ACCOUNT_TYPE", "ADDRESS_1", "ADDRESS_2", "ADDRESS_3", "ADDRESS_4", "ADDRESS_5", "ANALYSIS_1", "ANALYSIS_2", "ANALYSIS_3", "BACSforACS", "BACS_REFERENCEforACS", "BALANCE", "BUILD_SOCIETY_REFfor", "BUILDING_SOCIETYuses", "CAN_APPLY_CHARGES", "CONTACT_NAME", "COUNTRY_CODE", "CREDIT_APP_RECEIVEDif", "CREDIT_APPLIED_FOR", "CREDIT_BF", "CREDIT_BUREAU", "CREDIT_CARD_NO", "CREDIT_CF", "CREDIT_LIMIT", "CREDIT_MTH1", "CREDIT_MTH10", "CREDIT_MTH11", "CREDIT_MTH12", "CREDIT_MTH2", "CREDIT_MTH3", "CREDIT_MTH4", "CREDIT_MTH5", "CREDIT_MTH6", "CREDIT_MTH7", "CREDIT_MTH8", "CREDIT_REFERENCE", "CURRENCY", "DATE_CREDIT_APP_RECEIVED", "DEF_NOM_CODE", "DEF_TAX_CODE", "DEL_ADDRESS_1", "DEL_ADDRESS_2", "CREDIT_MTH9", "DEL_ADDRESS_3", "DEL_ADDRESS_4", "DEL_ADDRESS_5", "DEL_CONTACT_NAME", "DEL_FAX", "DEL_NAME", "DEL_TELEPHONE", "DELETED_FLAG", "DEPT_NUMBER", "DISCOUNT_RATE", "DISCOUNT_TYPE", "E_MAIL", "EC_CODEC", "EXTERNAL_USAGE", "FAX", "FIRST_HEADERof", "FIRST_INVOICE", "HOLD_MAIL", "INVOICE_BF", "INVOICE_CF", "INVOICE_MTH1", "INVOICE_MTH10", "INVOICE_MTH11", "INVOICE_MTH12", "INVOICE_MTH2", "INVOICE_MTH3", "INVOICE_MTH4", "INVOICE_MTH5", "INVOICE_MTH6", "INVOICE_MTH7", "INVOICE_MTH8", "INVOICE_MTH9", "LAST_CREDIT_REV", "LAST_HEADERof", "LAST_INV_DATE", "LAST_PAY_DATE", "MEMO_OFFSETin", "MEMO_SIZE", "MODIFY", "NAME", "NEXT_CREDIT_REV", "NO_OF_HEADER", "OVERRIDE_PRODUCT_TAX", "PAYMENT_BF", "PAYMENT_CF", "PAYMENT_DUE_DAYS", "PAYMENT_MTH1", "PAYMENT_MTH10", "PAYMENT_MTH11", "PAYMENT_MTH12", "PAYMENT_MTH2", "PAYMENT_MTH3", "PAYMENT_MTH4", "PAYMENT_MTH5", "PAYMENT_MTH6", "PAYMENT_MTH7", "PAYMENT_MTH8", "PAYMENT_MTH9", "PRICE_LIST_REF", "PRIOR_YEARTD", "SALES_REPof", "SETTLEMENT_DISC_RATE", "SETTLEMENT_DUE_DAYS", "TELEPHONE", "TELEPHONE_2", "TERMS", "TERMS_AGREED_FLAG", "TRADE_CONTACT", "TURNOVER_MTD", "TURNOVER_YTD", "VAT_REG_NUMBERAT", "WWWWW" 
#endregion data 
};


        static string[] purchase_headers = {  
#region data 
"ACCOUNT_MANAGER", "ACCOUNT_ON_HOLD", "ACCOUNT_OPENED", "ACCOUNT_REF", "ACCOUNT_STATUS", "ACCOUNT_TYPE", "ADDRESS_1", "ADDRESS_2", "ADDRESS_3", "ADDRESS_4", "ADDRESS_5", "ANALYSIS_1", "ANALYSIS_2", "ANALYSIS_3", "BACS", "BACS_REFERENCE", "BALANCE", "BANK_ACCOUNT_NAME", "BANK_ACCOUNT_NUMBER", "BANK_ADDRESS_1", "BANK_ADDRESS_2", "BANK_ADDRESS_3", "BANK_ADDRESS_4", "BANK_ADDRESS_5", "BANK_NAME", "BANK_SORT_CODE", "BUILD_SOCIETY_REF", "BUILDING_SOCIETY", "CAN_APPLY_CHARGES", "CONTACT_NAME", "COUNTRY_CODE", "CREDIT_APP_RECEIVED", "CREDIT_APPLIED_FOR", "CREDIT_BF", "CREDIT_BUREAU", "CREDIT_CARD_NO", "CREDIT_CF", "CREDIT_LIMIT", "CREDIT_MTH", "CREDIT_MTH0", "CREDIT_MTH1", "CREDIT_MTH2", "CREDIT_MTH3", "CREDIT_MTH4", "CREDIT_MTH5", "CREDIT_MTH6", "CREDIT_MTH7", "CREDIT_MTH8", "CREDIT_MTH9", "CREDIT_MTH10", "CREDIT_MTH11", "CREDIT_MTH12", "CREDIT_REFERENCE", "CURRENCY", "DATE_CREDIT_APP_RECEIVED", "DEF_NOM_CODE", "DEF_TAX_CODE", "DEL_ADDRESS_1", "DEL_ADDRESS_2", "DEL_ADDRESS_3", "DEL_ADDRESS_4", "DEL_ADDRESS_5", "DEL_CONTACT_NAME", "DEL_FAX", "DEL_NAME", "DEL_TELEPHONE", "DELETED_FLAG", "DEPT_NUMBER", "DISCOUNT_RATE", "DISCOUNT_TYPE", "E_MAIL", "EC_CODE", "EXTERNAL_USAGE", "FAX", "FIRST_HEADER", "FIRST_INVOICE", "HOLD_MAIL", "INVOICE_BF", "INVOICE_CF", "INVOICE_MTH", "INVOICE_MTH0", "INVOICE_MTH1", "INVOICE_MTH2", "INVOICE_MTH3", "INVOICE_MTH4", "INVOICE_MTH5", "INVOICE_MTH6", "INVOICE_MTH7", "INVOICE_MTH8", "INVOICE_MTH9", "INVOICE_MTH10", "INVOICE_MTH11", "INVOICE_MTH12", "LAST_CREDIT_REV", "LAST_HEADER", "LAST_INV_DATE", "LAST_PAY_DATE", "MEMO_OFFSET", "MEMO_SIZE", "MODIFY", "NAME", "NEXT_CREDIT_REV", "NO_OF_HEADER", "OVERRIDE_PRODUCT_TAX", "PAYMENT_BF", "PAYMENT_CF", "PAYMENT_DUE_DAYS", "PAYMENT_MTH12", "PAYMENT_MTH11", "PAYMENT_MTH0", "PAYMENT_MTH1", "PAYMENT_MTH2", "PAYMENT_MTH3", "PAYMENT_MTH4", "PAYMENT_MTH5", "PAYMENT_MTH6", "PAYMENT_MTH7", "PAYMENT_MTH8", "PAYMENT_MTH9", "PAYMENT_MTH10", "PRICE_LIST_REF", "PRIOR_YEAR", "SALES_REP", "SETTLEMENT_DISC_RATE", "SETTLEMENT_DUE_DAYS", "TELEPHONE", "TELEPHONE_2", "TERMS", "TERMS_AGREED_FLAG", "TRADE_CONTACT", "TURNOVER_MTD", "TURNOVER_YTD", "VAT_REG_NUMBER", "WWW" 
#endregion data 
};


        static string[] expense_headers = {  
#region data 
"ACCOUNT_REF", "ACCOUNT_TYPE", "AUDIT_REF", "BALANCE", "BALANCE_BF", "BALANCE_FUTURE", "BALANCE_MTH1", "BALANCE_MTH10", "BALANCE_MTH11", "BALANCE_MTH12", "BALANCE_MTH2", "BALANCE_MTH3", "BALANCE_MTH4", "BALANCE_MTH5", "BALANCE_MTH6", "BALANCE_MTH7", "BALANCE_MTH8", "BALANCE_MTH9", "BUDGET_MTH1", "BUDGET_MTH10", "BUDGET_MTH11", "BUDGET_MTH12", "BUDGET_MTH2", "BUDGET_MTH3", "BUDGET_MTH4", "BUDGET_MTH5", "BUDGET_MTH6", "BUDGET_MTH7", "BUDGET_MTH8", "BUDGET_MTH9", "CREDIT_BF", "CREDIT_FUTURE", "CREDIT_MTH1", "CREDIT_MTH10", "CREDIT_MTH11", "CREDIT_MTH12", "CREDIT_MTH2", "CREDIT_MTH3", "CREDIT_MTH4", "CREDIT_MTH5", "CREDIT_MTH6", "CREDIT_MTH7", "CREDIT_MTH8", "CREDIT_MTH9", "DEBIT_BF", "DEBIT_FUTURE", "DEBIT_MTH1", "DEBIT_MTH10", "DEBIT_MTH11", "DEBIT_MTH12", "DEBIT_MTH2", "DEBIT_MTH3", "DEBIT_MTH4", "DEBIT_MTH5", "DEBIT_MTH6", "DEBIT_MTH7", "DEBIT_MTH8", "DEBIT_MTH9", "DELETED_FLAG", "EXTERNAL_USAGE", "FIRST_SPLIT", "LAST_SPLIT", "NAME", "NO_OF_SPLIT", "PRIOR_YR2_MTH1", "PRIOR_YR2_MTH10", "PRIOR_YR2_MTH11", "PRIOR_YR2_MTH12", "PRIOR_YR2_MTH2", "PRIOR_YR2_MTH3", "PRIOR_YR2_MTH4", "PRIOR_YR2_MTH5", "PRIOR_YR2_MTH6", "PRIOR_YR2_MTH7", "PRIOR_YR2_MTH8", "PRIOR_YR2_MTH9", "PRIOR_YR3_MTH1", "PRIOR_YR3_MTH10", "PRIOR_YR3_MTH11", "PRIOR_YR3_MTH12", "PRIOR_YR3_MTH2", "PRIOR_YR3_MTH3", "PRIOR_YR3_MTH4", "PRIOR_YR3_MTH5", "PRIOR_YR3_MTH6", "PRIOR_YR3_MTH7", "PRIOR_YR3_MTH8", "PRIOR_YR3_MTH9", "PRIOR_YR4_MTH1", "PRIOR_YR4_MTH10", "PRIOR_YR4_MTH11", "PRIOR_YR4_MTH12", "PRIOR_YR4_MTH2", "PRIOR_YR4_MTH3", "PRIOR_YR4_MTH4", "PRIOR_YR4_MTH5", "PRIOR_YR4_MTH6", "PRIOR_YR4_MTH7", "PRIOR_YR4_MTH8", "PRIOR_YR4_MTH9", "PRIOR_YR5_MTH1", "PRIOR_YR5_MTH10", "PRIOR_YR5_MTH11", "PRIOR_YR5_MTH12", "PRIOR_YR5_MTH2", "PRIOR_YR5_MTH3", "PRIOR_YR5_MTH4", "PRIOR_YR5_MTH5", "PRIOR_YR5_MTH6", "PRIOR_YR5_MTH7", "PRIOR_YR5_MTH8", "PRIOR_YR5_MTH9", "PRIOR_YR_MTH1", "PRIOR_YR_MTH10", "PRIOR_YR_MTH11", "PRIOR_YR_MTH12", "PRIOR_YR_MTH2", "PRIOR_YR_MTH3", "PRIOR_YR_MTH4", "PRIOR_YR_MTH5", "PRIOR_YR_MTH6", "PRIOR_YR_MTH7", "PRIOR_YR_MTH8", "PRIOR_YR_MTH9", "QUICK_RATIO_FLAG" 
#endregion data 
};


        static string[] bank_headers = {
#region data 
"ACCOUNT_NAME", "ACCOUNT_NUMBER", "ACCOUNT_REF", "ACCOUNT_TYPE", "ADDRESS_1", "ADDRESS_2", "ADDRESS_3", "ADDRESS_4", "ADDRESS_5", "BANK_REF", "CONTACT_NAME", "CURRENCY", "DELETED_FLAG", "E_MAIL", "ELEC_TRANS", "EXPIRY_DATE", "EXTERNAL_USAGE", "FAX", "FIRST_SPLIT", "FOREIGN_BALANCE", "LAST_SPLIT", "NAME", "NEXT_CHQ_NO", "NEXT_DEP_NO", "NEXT_WITHDRAWAL_NO", "NO_OF_SPLIT", "NO_OF_TRAN", "NO_OF_UNRECONCILED_ITEMS", "NO_RECONCILIATION_FLAG", "OVERDRAFT_LIMIT", "SORT_CODE", "TELEPHONE", "WWW"};
#endregion};



        static string[] stock_headers = {  
#region data
"ASSEMBLY_LEVEL", "AVERAGE_COST_PRICE", "BUDGET_QTY_SOLD_BF", "BUDGET_QTY_SOLD_FUTURE", "BUDGET_QTY_SOLD_MTH1", "BUDGET_QTY_SOLD_MTH10", "BUDGET_QTY_SOLD_MTH11", "BUDGET_QTY_SOLD_MTH12", "BUDGET_QTY_SOLD_MTH2", "BUDGET_QTY_SOLD_MTH3", "BUDGET_QTY_SOLD_MTH4", "BUDGET_QTY_SOLD_MTH5", "BUDGET_QTY_SOLD_MTH6", "BUDGET_QTY_SOLD_MTH7", "BUDGET_QTY_SOLD_MTH8", "BUDGET_QTY_SOLD_MTH9", "BUDGET_SALES_BF", "BUDGET_SALES_FUTURE", "BUDGET_SALES_MTH1", "BUDGET_SALES_MTH10", "BUDGET_SALES_MTH11", "BUDGET_SALES_MTH12", "BUDGET_SALES_MTH2", "BUDGET_SALES_MTH3", "BUDGET_SALES_MTH4", "BUDGET_SALES_MTH5", "BUDGET_SALES_MTH6", "BUDGET_SALES_MTH7", "BUDGET_SALES_MTH8", "BUDGET_SALES_MTH9", "COMMODITY_CODE", "COMPONENT_CODE_1", "COMPONENT_CODE_10", "COMPONENT_CODE_2", "COMPONENT_CODE_3", "COMPONENT_CODE_4", "COMPONENT_CODE_5", "COMPONENT_CODE_6", "COMPONENT_CODE_7", "COMPONENT_CODE_8", "COMPONENT_CODE_9", "COMPONENT_QTY_1", "COMPONENT_QTY_10", "COMPONENT_QTY_2", "COMPONENT_QTY_3", "COMPONENT_QTY_4", "COMPONENT_QTY_5", "COMPONENT_QTY_6", "COMPONENT_QTY_7", "COMPONENT_QTY_8", "COMPONENT_QTY_9", "COST_BF", "COST_FUTURE", "COST_MTH1", "COST_MTH10", "COST_MTH11", "COST_MTH12", "COST_MTH2", "COST_MTH3", "COST_MTH4", "COST_MTH5", "COST_MTH6", "COST_MTH7", "COST_MTH8", "COST_MTH9", "CUSTOM_1", "CUSTOM_2", "CUSTOM_3", "DELETED_FLAG", "DEPT_NUMBER", "DESCRIPTION", "DISC_A_LEVEL_10_QTY", "DISC_A_LEVEL_10_RATE", "DISC_A_LEVEL_1_QTY", "DISC_A_LEVEL_1_RATE", "DISC_A_LEVEL_2_QTY", "DISC_A_LEVEL_2_RATE", "DISC_A_LEVEL_3_QTY", "DISC_A_LEVEL_3_RATE", "DISC_A_LEVEL_4_QTY", "DISC_A_LEVEL_4_RATE", "DISC_A_LEVEL_5_QTY", "DISC_A_LEVEL_5_RATE", "DISC_A_LEVEL_6_QTY", "DISC_A_LEVEL_6_RATE", "DISC_A_LEVEL_7_QTY", "DISC_A_LEVEL_7_RATE", "DISC_A_LEVEL_8_QTY", "DISC_A_LEVEL_8_RATE", "DISC_A_LEVEL_9_QTY", "DISC_A_LEVEL_9_RATE", "DISC_B_LEVEL_10_QTY", "DISC_B_LEVEL_10_RATE", "DISC_B_LEVEL_1_QTY", "DISC_B_LEVEL_1_RATE", "DISC_B_LEVEL_2_QTY", "DISC_B_LEVEL_2_RATE", "DISC_B_LEVEL_3_QTY", "DISC_B_LEVEL_3_RATE", "DISC_B_LEVEL_4_QTY", "DISC_B_LEVEL_4_RATE", "DISC_B_LEVEL_5_QTY", "DISC_B_LEVEL_5_RATE", "DISC_B_LEVEL_6_QTY", "DISC_B_LEVEL_6_RATE", "DISC_B_LEVEL_7_QTY", "DISC_B_LEVEL_7_RATE", "DISC_B_LEVEL_8_QTY", "DISC_B_LEVEL_8_RATE", "DISC_B_LEVEL_9_QTY", "DISC_B_LEVEL_9_RATE", "DISC_C_LEVEL_10_QTY", "DISC_C_LEVEL_10_RATE", "DISC_C_LEVEL_1_QTY", "DISC_C_LEVEL_1_RATE", "DISC_C_LEVEL_2_QTY", "DISC_C_LEVEL_2_RATE", "DISC_C_LEVEL_3_QTY", "DISC_C_LEVEL_3_RATE", "DISC_C_LEVEL_4_QTY", "DISC_C_LEVEL_4_RATE", "DISC_C_LEVEL_5_QTY", "DISC_C_LEVEL_5_RATE", "DISC_C_LEVEL_6_QTY", "DISC_C_LEVEL_6_RATE", "DISC_C_LEVEL_7_QTY", "DISC_C_LEVEL_7_RATE", "DISC_C_LEVEL_8_QTY", "DISC_C_LEVEL_8_RATE", "DISC_C_LEVEL_9_QTY", "DISC_C_LEVEL_9_RATE", "DISC_D_LEVEL_10_QTY", "DISC_D_LEVEL_10_RATE", "DISC_D_LEVEL_1_QTY", "DISC_D_LEVEL_1_RATE", "DISC_D_LEVEL_2_QTY", "DISC_D_LEVEL_2_RATE", "DISC_D_LEVEL_3_QTY", "DISC_D_LEVEL_3_RATE", "DISC_D_LEVEL_4_QTY", "DISC_D_LEVEL_4_RATE", "DISC_D_LEVEL_5_QTY", "DISC_D_LEVEL_5_RATE", "DISC_D_LEVEL_6_QTY", "DISC_D_LEVEL_6_RATE", "DISC_D_LEVEL_7_QTY", "DISC_D_LEVEL_7_RATE", "DISC_D_LEVEL_8_QTY", "DISC_D_LEVEL_8_RATE", "DISC_D_LEVEL_9_QTY", "DISC_D_LEVEL_9_RATE", "DISC_E_LEVEL_10_QTY", "DISC_E_LEVEL_10_RATE", "DISC_E_LEVEL_1_QTY", "DISC_E_LEVEL_1_RATE", "DISC_E_LEVEL_2_QTY", "DISC_E_LEVEL_2_RATE", "DISC_E_LEVEL_3_QTY", "DISC_E_LEVEL_3_RATE", "DISC_E_LEVEL_4_QTY", "DISC_E_LEVEL_4_RATE", "DISC_E_LEVEL_5_QTY", "DISC_E_LEVEL_5_RATE", "DISC_E_LEVEL_6_QTY", "DISC_E_LEVEL_6_RATE", "DISC_E_LEVEL_7_QTY", "DISC_E_LEVEL_7_RATE", "DISC_E_LEVEL_8_QTY", "DISC_E_LEVEL_8_RATE", "DISC_E_LEVEL_9_QTY", "DISC_E_LEVEL_9_RATE", "EXTERNAL_USAGE", "FIRST_TRAN", "IGNORE_STK_LVL_FLAG", "ITEM_TYPE", "LAST_PURCHASE_DATE", "LAST_PURCHASE_PRICE", "LAST_SALE_DATE", "LAST_TRAN", "LINK_LEVEL", "LOCATION", "NO_OF_TRAN", "NOMINAL_CODE", "PRIOR_YR_COST_BF", "PRIOR_YR_COST_FUTURE", "PRIOR_YR_COST_MTH1", "PRIOR_YR_COST_MTH10", "PRIOR_YR_COST_MTH11", "PRIOR_YR_COST_MTH12", "PRIOR_YR_COST_MTH2", "PRIOR_YR_COST_MTH3", "PRIOR_YR_COST_MTH4", "PRIOR_YR_COST_MTH5", "PRIOR_YR_COST_MTH6", "PRIOR_YR_COST_MTH7", "PRIOR_YR_COST_MTH8", "PRIOR_YR_COST_MTH9", "PRIOR_YR_QTY_SOLD_BF", "PRIOR_YR_QTY_SOLD_FUTURE", "PRIOR_YR_QTY_SOLD_MTH1", "PRIOR_YR_QTY_SOLD_MTH10", "PRIOR_YR_QTY_SOLD_MTH11", "PRIOR_YR_QTY_SOLD_MTH12", "PRIOR_YR_QTY_SOLD_MTH2", "PRIOR_YR_QTY_SOLD_MTH3", "PRIOR_YR_QTY_SOLD_MTH4", "PRIOR_YR_QTY_SOLD_MTH5", "PRIOR_YR_QTY_SOLD_MTH6", "PRIOR_YR_QTY_SOLD_MTH7", "PRIOR_YR_QTY_SOLD_MTH8", "PRIOR_YR_QTY_SOLD_MTH9", "PRIOR_YR_SALES_BF", "PRIOR_YR_SALES_FUTURE", "PRIOR_YR_SALES_MTH1", "PRIOR_YR_SALES_MTH10", "PRIOR_YR_SALES_MTH11", "PRIOR_YR_SALES_MTH12", "PRIOR_YR_SALES_MTH2", "PRIOR_YR_SALES_MTH3", "PRIOR_YR_SALES_MTH4", "PRIOR_YR_SALES_MTH5", "PRIOR_YR_SALES_MTH6", "PRIOR_YR_SALES_MTH7", "PRIOR_YR_SALES_MTH8", "PRIOR_YR_SALES_MTH9", "PURCHASE_REF", "QTY_ALLOCATED", "QTY_IN_STOCK", "QTY_LAST_ORDER", "QTY_LAST_STOCK_TAKE", "QTY_ON_ORDER", "QTY_REORDER", "QTY_REORDER_LEVEL", "QTY_SOLD_BF", "QTY_SOLD_FUTURE", "QTY_SOLD_MTH1", "QTY_SOLD_MTH10", "QTY_SOLD_MTH11", "QTY_SOLD_MTH12", "QTY_SOLD_MTH2", "QTY_SOLD_MTH3", "QTY_SOLD_MTH4", "QTY_SOLD_MTH5", "QTY_SOLD_MTH6", "QTY_SOLD_MTH7", "QTY_SOLD_MTH8", "QTY_SOLD_MTH9", "SALES_BF", "SALES_FUTURE", "SALES_MTH1", "SALES_MTH10", "SALES_MTH11", "SALES_MTH12", "SALES_MTH2", "SALES_MTH3", "SALES_MTH4", "SALES_MTH5", "SALES_MTH6", "SALES_MTH7", "SALES_MTH8", "SALES_MTH9", "SALES_PRICE", "STOCK_CAT", "STOCK_CODE", "STOCK_TAKE_DATE", "SUPPLIER_PART_NUMBER", "TAX_CODE", "UNIT_OF_SALE", "UNIT_WEIGHT", "WEB_DESCRIPTION", "WEB_IMAGE", "WEB_LONGDESCRIPTION", "WEB_PUBLISH", "WEB_SPECIAL_OFFER"};
#endregion};

        //f55fb663-21e1-42d8-8767-0a891783243e

        static string[] document_headers = {
#region data
#endregion
                                           };

    }
}