using System.Collections.Generic;

using Fairweather.Service;

namespace Common.Sage
{
    public static partial class Sage_Fields
    {
        static public class StockTran
        {
            // autogenerated: C:\Users\Fairweather\Desktop\Generation\sage_strings.pl
            static public readonly Sage_Field
            COST_PRICE = Double("COST_PRICE", "Cost Price", 8) // Opt
            , DATE = Date("DATE", "Transaction Date", 2) // Req
            , DETAILS = String("DETAILS", "Details", 60) // Opt
            , NEXT_ITEM = Int("NEXT_ITEM", "Previous Tran", 4) // Opt
            , PREV_ITEM = Int("PREV_ITEM", "Next Tran", 4) // Opt
            , QTY_USED = Double("QTY_USED", "Quantity Used", 8) // Opt
            , QUANTITY = Double("QUANTITY", "Quantity", 8) // Req
            , REFERENCE = String("REFERENCE", "Transaction Reference", 8) // Opt
            , RESERVED = SByte("RESERVED", "Reserved", 1) // Opt
            , SALES_PRICE = Double("SALES_PRICE", "Sales Price", 8) // Opt
            , STOCK_CODE = String("STOCK_CODE", "Stock Code", 30) // Req
            , TYPE = SByte("TYPE", "Transaction Type", 1) // Req
            ;

            public static Dict_ro<string, Sage_Field>
            Fields { get { return fields; } }

            static readonly Dict_ro<string, Sage_Field>
            fields = Make(COST_PRICE
            , DATE
            , DETAILS
            , NEXT_ITEM
            , PREV_ITEM
            , QTY_USED
            , QUANTITY
            , REFERENCE
            , RESERVED
            , SALES_PRICE
            , STOCK_CODE
            , TYPE
            );
        }
    }
}
