using System.Collections.Generic;

using Fairweather.Service;

namespace Common.Sage
{
    public static partial class Sage_Fields
    {
        static public class HeaderData
        {
            // autogenerated: C:\Users\Fairweather\Desktop\Generation\sage_strings.pl
            public static readonly Sage_Field
            ACCOUNT_REF = String("ACCOUNT_REF", "Sales/Purchase/Bank Account Reference", 8) // Req
            , AMOUNT_PAID = Double("AMOUNT_PAID", "Total Amount Paid", 8) // Sys
            , BANK_CODE = String("BANK_CODE", "Bank Account Reference", 8) // Req
            , BANK_FLAG = SByte("BANK_FLAG", "Bank Reconciled Flag", 1) // Opt
            , CURRENCY = SByte("CURRENCY", "Currency for Transaction", 1) // Opt
            , CURRENCY_USED = SByte("CURRENCY_USED", "Currency Used", 1) // Opt
            , DATE = Date("DATE", "Transaction Date", 2) // Req
            , DATE_DUE = Date("DATE_DUE", "Date Invoice is Due for Payment", 2) // Sys
            , DATE_LAST_CHARGE = Date("DATE_LAST_CHARGE", "Date Interest Last Charged", 2) // Opt
            , DELETED_FLAG = Short("DELETED_FLAG", "Transaction Deleted Flag", 2) // Opt
            , DETAILS = String("DETAILS", "Details", 60) // Opt
            , ELEC_TRANS = Short("ELEC_TRANS", "Electronic Transaction Flag", 2) // Opt
            , EURO_GROSS = Double("EURO_GROSS", "Euro Gross Amount", 8) // Req
            , EURO_RATE = Double("EURO_RATE", "Euro Rate", 8) // Req
            , FINANCE_CHARGE = SByte("FINANCE_CHARGE", "Finance Charge Flag", 1) // Opt
            , FIRST_SPLIT = Int("FIRST_SPLIT", "Item Number", 4) // Sys
            , FOREIGN_AMOUNT_PAID = Double("FOREIGN_AMOUNT_PAID", "Foreign Total Amount Paid", 8) // Opt
            , FOREIGN_GROSS = Double("FOREIGN_GROSS", "Foreign Gross Amount", 8) // Req
            , FOREIGN_NET_AMOUNT = Double("FOREIGN_NET_AMOUNT", "Foreign Net Amount", 8) // Opt
            , FOREIGN_RATE = Double("FOREIGN_RATE", "Foreign Rate For Euro Currency", 8) // Req
            , FOREIGN_TAX_AMOUNT = Double("FOREIGN_TAX_AMOUNT", "Foreign Tax Amount", 8) // Opt
            , INTEREST_RATE = Double("INTEREST_RATE", "Interest Rate to Charge", 8) // Req
            , INV_REF = String("INV_REF", "Invoice Reference Number", 8) // Opt
            , JOB_REFERENCE = String("JOB_REFERENCE", "Job Costing Reference", 20) // Opt
            , LAST_SPLIT = Int("LAST_SPLIT", "Item Number", 4) // Sys
            , NET_AMOUNT = Double("NET_AMOUNT", "Net Amount", 8) // Req
            , NEXT_ACCOUNT = Int("NEXT_ACCOUNT", "Record Number for Next Account", 4) // Sys
            , NEXT_BANK = Int("NEXT_BANK", "Record Number for Next Bank", 4) // Sys
            , NO_DISPUTED = Short("NO_DISPUTED", "Number of Disputed Splits", 2) // Opt
            , NO_OF_SPLIT = Int("NO_OF_SPLIT", "Number of Splits", 4) // Sys
            , PAID_FLAG = SByte("PAID_FLAG", "Transaction Paid Flag", 1) // Opt
            , POSTED_DATE = Date("POSTED_DATE", "Posting Date", 2) // Opt
            , POSTING_LOCATION = Short("POSTING_LOCATION", "Location Transaction Posted From", 2) // Opt
            , PREV_ACCOUNT = Int("PREV_ACCOUNT", "Record Number for Previous Account", 4) // Sys
            , PREV_BANK = Int("PREV_BANK", "Record Number for Previous Bank", 4) // Sys
            , PRINTED_FLAG = SByte("PRINTED_FLAG", "Printed Flag", 1) // Opt
            , RECON_DATE = Date("RECON_DATE", "Date Transaction was Reconciled", 2) // Opt
            , TAX_AMOUNT = Double("TAX_AMOUNT", "Tax Amount", 8) // Opt
            , TYPE = SByte("TYPE", "Transaction Type", 1) // Req
            , UNIQUE_REF = Int("UNIQUE_REF", "Header Number", 4) // Sys
            , USER_NAME = String("USER_NAME", "User Name", 32) // Opt
            , VAT_FLAG = SByte("VAT_FLAG", "Vat Flag", 1) // Opt
            ;

            public static Dict_ro<string, Sage_Field>
            Fields { get { return fields; } }

            static readonly Dict_ro<string, Sage_Field>
            fields = Make(ACCOUNT_REF
            , AMOUNT_PAID
            , BANK_CODE
            , BANK_FLAG
            , CURRENCY
            , CURRENCY_USED
            , DATE
            , DATE_DUE
            , DATE_LAST_CHARGE
            , DELETED_FLAG
            , DETAILS
            , ELEC_TRANS
            , EURO_GROSS
            , EURO_RATE
            , FINANCE_CHARGE
            , FIRST_SPLIT
            , FOREIGN_AMOUNT_PAID
            , FOREIGN_GROSS
            , FOREIGN_NET_AMOUNT
            , FOREIGN_RATE
            , FOREIGN_TAX_AMOUNT
            , INTEREST_RATE
            , INV_REF
            , JOB_REFERENCE
            , LAST_SPLIT
            , NET_AMOUNT
            , NEXT_ACCOUNT
            , NEXT_BANK
            , NO_DISPUTED
            , NO_OF_SPLIT
            , PAID_FLAG
            , POSTED_DATE
            , POSTING_LOCATION
            , PREV_ACCOUNT
            , PREV_BANK
            , PRINTED_FLAG
            , RECON_DATE
            , TAX_AMOUNT
            , TYPE
            , UNIQUE_REF
            , USER_NAME
            , VAT_FLAG
            );
        }
    }
}
