using System.Collections.Generic;

using Fairweather.Service;

namespace Common.Sage
{
    public static partial class Sage_Fields
    {
        static public class NominalRecord
        {
            // autogenerated: C:\Users\Fairweather\Desktop\codegen\sage_strings.pl
            static public readonly Sage_Field
            ACCOUNT_REF = String("ACCOUNT_REF", "Account Code", 8) // Req
            , ACCOUNT_TYPE = SByte("ACCOUNT_TYPE", "Account Type Code", 1) // Opt
            , AUDIT_REF = String("AUDIT_REF", "Incomplete Records Reference", 20) // Opt
            , BALANCE = Double("BALANCE", "Balance", 8) // Opt
            , BALANCE_BF = Double("BALANCE_BF", "Balance Brought Forward", 8) // Opt
            , BALANCE_FUTURE = Double("BALANCE_FUTURE", "Balance Future", 8) // Opt
            , BALANCE_MTH1 = Double("BALANCE_MTH1", "Balance Month 1", 8) // Opt
            , BALANCE_MTH10 = Double("BALANCE_MTH10", "Balance Month 10", 8) // Opt
            , BALANCE_MTH11 = Double("BALANCE_MTH11", "Balance Month 11", 8) // Opt
            , BALANCE_MTH12 = Double("BALANCE_MTH12", "Balance Month 12", 8) // Opt
            , BALANCE_MTH2 = Double("BALANCE_MTH2", "Balance Month 2", 8) // Opt
            , BALANCE_MTH3 = Double("BALANCE_MTH3", "Balance Month 3", 8) // Opt
            , BALANCE_MTH4 = Double("BALANCE_MTH4", "Balance Month 4", 8) // Opt
            , BALANCE_MTH5 = Double("BALANCE_MTH5", "Balance Month 5", 8) // Opt
            , BALANCE_MTH6 = Double("BALANCE_MTH6", "Balance Month 6", 8) // Opt
            , BALANCE_MTH7 = Double("BALANCE_MTH7", "Balance Month 7", 8) // Opt
            , BALANCE_MTH8 = Double("BALANCE_MTH8", "Balance Month 8", 8) // Opt
            , BALANCE_MTH9 = Double("BALANCE_MTH9", "Balance Month 9", 8) // Opt
            , BUDGET_MTH1 = Double("BUDGET_MTH1", "Budget Month 1", 8) // Opt
            , BUDGET_MTH10 = Double("BUDGET_MTH10", "Budget Month 10", 8) // Opt
            , BUDGET_MTH11 = Double("BUDGET_MTH11", "Budget Month 11", 8) // Opt
            , BUDGET_MTH12 = Double("BUDGET_MTH12", "Budget Month 12", 8) // Opt
            , BUDGET_MTH2 = Double("BUDGET_MTH2", "Budget Month 2", 8) // Opt
            , BUDGET_MTH3 = Double("BUDGET_MTH3", "Budget Month 3", 8) // Opt
            , BUDGET_MTH4 = Double("BUDGET_MTH4", "Budget Month 4", 8) // Opt
            , BUDGET_MTH5 = Double("BUDGET_MTH5", "Budget Month 5", 8) // Opt
            , BUDGET_MTH6 = Double("BUDGET_MTH6", "Budget Month 6", 8) // Opt
            , BUDGET_MTH7 = Double("BUDGET_MTH7", "Budget Month 7", 8) // Opt
            , BUDGET_MTH8 = Double("BUDGET_MTH8", "Budget Month 8", 8) // Opt
            , BUDGET_MTH9 = Double("BUDGET_MTH9", "Budget Month 9", 8) // Opt
            , CREDIT_BF = Double("CREDIT_BF", "Credit Brought Forward", 8) // Opt
            , CREDIT_FUTURE = Double("CREDIT_FUTURE", "Credit for Future", 8) // Opt
            , CREDIT_MTH1 = Double("CREDIT_MTH1", "Credit Month 1", 8) // Opt
            , CREDIT_MTH10 = Double("CREDIT_MTH10", "Credit Month 10", 8) // Opt
            , CREDIT_MTH11 = Double("CREDIT_MTH11", "Credit Month 11", 8) // Opt
            , CREDIT_MTH12 = Double("CREDIT_MTH12", "Credit Month 12", 8) // Opt
            , CREDIT_MTH2 = Double("CREDIT_MTH2", "Credit Month 2", 8) // Opt
            , CREDIT_MTH3 = Double("CREDIT_MTH3", "Credit Month 3", 8) // Opt
            , CREDIT_MTH4 = Double("CREDIT_MTH4", "Credit Month 4", 8) // Opt
            , CREDIT_MTH5 = Double("CREDIT_MTH5", "Credit Month 5", 8) // Opt
            , CREDIT_MTH6 = Double("CREDIT_MTH6", "Credit Month 6", 8) // Opt
            , CREDIT_MTH7 = Double("CREDIT_MTH7", "Credit Month 7", 8) // Opt
            , CREDIT_MTH8 = Double("CREDIT_MTH8", "Credit Month 8", 8) // Opt
            , CREDIT_MTH9 = Double("CREDIT_MTH9", "Credit Month 9", 8) // Opt
            , DEBIT_BF = Double("DEBIT_BF", "Debit Brought Forward", 8) // Opt
            , DEBIT_FUTURE = Double("DEBIT_FUTURE", "Debit for Future", 8) // Opt
            , DEBIT_MTH1 = Double("DEBIT_MTH1", "Debit Month 1", 8) // Opt
            , DEBIT_MTH10 = Double("DEBIT_MTH10", "Debit Month 10", 8) // Opt
            , DEBIT_MTH11 = Double("DEBIT_MTH11", "Debit Month 11", 8) // Opt
            , DEBIT_MTH12 = Double("DEBIT_MTH12", "Debit Month 12", 8) // Opt
            , DEBIT_MTH2 = Double("DEBIT_MTH2", "Debit Month 2", 8) // Opt
            , DEBIT_MTH3 = Double("DEBIT_MTH3", "Debit Month 3", 8) // Opt
            , DEBIT_MTH4 = Double("DEBIT_MTH4", "Debit Month 4", 8) // Opt
            , DEBIT_MTH5 = Double("DEBIT_MTH5", "Debit Month 5", 8) // Opt
            , DEBIT_MTH6 = Double("DEBIT_MTH6", "Debit Month 6", 8) // Opt
            , DEBIT_MTH7 = Double("DEBIT_MTH7", "Debit Month 7", 8) // Opt
            , DEBIT_MTH8 = Double("DEBIT_MTH8", "Debit Month 8", 8) // Opt
            , DEBIT_MTH9 = Double("DEBIT_MTH9", "Debit Month 9", 8) // Opt
            , DELETED_FLAG = Short("DELETED_FLAG", "Is Deleted", 2) // Opt
            , EXTERNAL_USAGE = Int("EXTERNAL_USAGE", "Number of External Usages", 4) // Opt
            , FIRST_SPLIT = Int("FIRST_SPLIT", "Record Number of First Split", 4) // Opt
            , LAST_SPLIT = Int("LAST_SPLIT", "Record Number of Last Split", 4) // Opt
            , NAME = String("NAME", "Name", 60) // Opt
            , NO_OF_SPLIT = Int("NO_OF_SPLIT", "Number of Splits", 4) // Opt
            , PRIOR_YR2_MTH1 = Double("PRIOR_YR2_MTH1", "Prior Year 2 Month 1", 8) // Opt
            , PRIOR_YR2_MTH10 = Double("PRIOR_YR2_MTH10", "Prior Year 2 Month 10", 8) // Opt
            , PRIOR_YR2_MTH11 = Double("PRIOR_YR2_MTH11", "Prior Year 2 Month 11", 8) // Opt
            , PRIOR_YR2_MTH12 = Double("PRIOR_YR2_MTH12", "Prior Year 2 Month 12", 8) // Opt
            , PRIOR_YR2_MTH2 = Double("PRIOR_YR2_MTH2", "Prior Year 2 Month 2", 8) // Opt
            , PRIOR_YR2_MTH3 = Double("PRIOR_YR2_MTH3", "Prior Year 2 Month 3", 8) // Opt
            , PRIOR_YR2_MTH4 = Double("PRIOR_YR2_MTH4", "Prior Year 2 Month 4", 8) // Opt
            , PRIOR_YR2_MTH5 = Double("PRIOR_YR2_MTH5", "Prior Year 2 Month 5", 8) // Opt
            , PRIOR_YR2_MTH6 = Double("PRIOR_YR2_MTH6", "Prior Year 2 Month 6", 8) // Opt
            , PRIOR_YR2_MTH7 = Double("PRIOR_YR2_MTH7", "Prior Year 2 Month 7", 8) // Opt
            , PRIOR_YR2_MTH8 = Double("PRIOR_YR2_MTH8", "Prior Year 2 Month 8", 8) // Opt
            , PRIOR_YR2_MTH9 = Double("PRIOR_YR2_MTH9", "Prior Year 2 Month 9", 8) // Opt
            , PRIOR_YR3_MTH1 = Double("PRIOR_YR3_MTH1", "Prior Year 3 Month 1", 8) // Opt
            , PRIOR_YR3_MTH10 = Double("PRIOR_YR3_MTH10", "Prior Year 3 Month 10", 8) // Opt
            , PRIOR_YR3_MTH11 = Double("PRIOR_YR3_MTH11", "Prior Year 3 Month 11", 8) // Opt
            , PRIOR_YR3_MTH12 = Double("PRIOR_YR3_MTH12", "Prior Year 3 Month 12", 8) // Opt
            , PRIOR_YR3_MTH2 = Double("PRIOR_YR3_MTH2", "Prior Year 3 Month 2", 8) // Opt
            , PRIOR_YR3_MTH3 = Double("PRIOR_YR3_MTH3", "Prior Year 3 Month 3", 8) // Opt
            , PRIOR_YR3_MTH4 = Double("PRIOR_YR3_MTH4", "Prior Year 3 Month 4", 8) // Opt
            , PRIOR_YR3_MTH5 = Double("PRIOR_YR3_MTH5", "Prior Year 3 Month 5", 8) // Opt
            , PRIOR_YR3_MTH6 = Double("PRIOR_YR3_MTH6", "Prior Year 3 Month 6", 8) // Opt
            , PRIOR_YR3_MTH7 = Double("PRIOR_YR3_MTH7", "Prior Year 3 Month 7", 8) // Opt
            , PRIOR_YR3_MTH8 = Double("PRIOR_YR3_MTH8", "Prior Year 3 Month 8", 8) // Opt
            , PRIOR_YR3_MTH9 = Double("PRIOR_YR3_MTH9", "Prior Year 3 Month 9", 8) // Opt
            , PRIOR_YR4_MTH1 = Double("PRIOR_YR4_MTH1", "Prior Year 4 Month 1", 8) // Opt
            , PRIOR_YR4_MTH10 = Double("PRIOR_YR4_MTH10", "Prior Year 4 Month 10", 8) // Opt
            , PRIOR_YR4_MTH11 = Double("PRIOR_YR4_MTH11", "Prior Year 4 Month 11", 8) // Opt
            , PRIOR_YR4_MTH12 = Double("PRIOR_YR4_MTH12", "Prior Year 4 Month 12", 8) // Opt
            , PRIOR_YR4_MTH2 = Double("PRIOR_YR4_MTH2", "Prior Year 4 Month 2", 8) // Opt
            , PRIOR_YR4_MTH3 = Double("PRIOR_YR4_MTH3", "Prior Year 4 Month 3", 8) // Opt
            , PRIOR_YR4_MTH4 = Double("PRIOR_YR4_MTH4", "Prior Year 4 Month 4", 8) // Opt
            , PRIOR_YR4_MTH5 = Double("PRIOR_YR4_MTH5", "Prior Year 4 Month 5", 8) // Opt
            , PRIOR_YR4_MTH6 = Double("PRIOR_YR4_MTH6", "Prior Year 4 Month 6", 8) // Opt
            , PRIOR_YR4_MTH7 = Double("PRIOR_YR4_MTH7", "Prior Year 4 Month 7", 8) // Opt
            , PRIOR_YR4_MTH8 = Double("PRIOR_YR4_MTH8", "Prior Year 4 Month 8", 8) // Opt
            , PRIOR_YR4_MTH9 = Double("PRIOR_YR4_MTH9", "Prior Year 4 Month 9", 8) // Opt
            , PRIOR_YR5_MTH1 = Double("PRIOR_YR5_MTH1", "Prior Year 5 Month 1", 8) // Opt
            , PRIOR_YR5_MTH10 = Double("PRIOR_YR5_MTH10", "Prior Year 5 Month 10", 8) // Opt
            , PRIOR_YR5_MTH11 = Double("PRIOR_YR5_MTH11", "Prior Year 5 Month 11", 8) // Opt
            , PRIOR_YR5_MTH12 = Double("PRIOR_YR5_MTH12", "Prior Year 5 Month 12", 8) // Opt
            , PRIOR_YR5_MTH2 = Double("PRIOR_YR5_MTH2", "Prior Year 5 Month 2", 8) // Opt
            , PRIOR_YR5_MTH3 = Double("PRIOR_YR5_MTH3", "Prior Year 5 Month 3", 8) // Opt
            , PRIOR_YR5_MTH4 = Double("PRIOR_YR5_MTH4", "Prior Year 5 Month 4", 8) // Opt
            , PRIOR_YR5_MTH5 = Double("PRIOR_YR5_MTH5", "Prior Year 5 Month 5", 8) // Opt
            , PRIOR_YR5_MTH6 = Double("PRIOR_YR5_MTH6", "Prior Year 5 Month 6", 8) // Opt
            , PRIOR_YR5_MTH7 = Double("PRIOR_YR5_MTH7", "Prior Year 5 Month 7", 8) // Opt
            , PRIOR_YR5_MTH8 = Double("PRIOR_YR5_MTH8", "Prior Year 5 Month 8", 8) // Opt
            , PRIOR_YR5_MTH9 = Double("PRIOR_YR5_MTH9", "Prior Year 5 Month 9", 8) // Opt
            , PRIOR_YR_MTH1 = Double("PRIOR_YR_MTH1", "Prior Year 1 Month 1", 8) // Opt
            , PRIOR_YR_MTH10 = Double("PRIOR_YR_MTH10", "Prior Year 1 Month 10", 8) // Opt
            , PRIOR_YR_MTH11 = Double("PRIOR_YR_MTH11", "Prior Year 1 Month 11", 8) // Opt
            , PRIOR_YR_MTH12 = Double("PRIOR_YR_MTH12", "Prior Year 1 Month 12", 8) // Opt
            , PRIOR_YR_MTH2 = Double("PRIOR_YR_MTH2", "Prior Year 1 Month 2", 8) // Opt
            , PRIOR_YR_MTH3 = Double("PRIOR_YR_MTH3", "Prior Year 1 Month 3", 8) // Opt
            , PRIOR_YR_MTH4 = Double("PRIOR_YR_MTH4", "Prior Year 1 Month 4", 8) // Opt
            , PRIOR_YR_MTH5 = Double("PRIOR_YR_MTH5", "Prior Year 1 Month 5", 8) // Opt
            , PRIOR_YR_MTH6 = Double("PRIOR_YR_MTH6", "Prior Year 1 Month 6", 8) // Opt
            , PRIOR_YR_MTH7 = Double("PRIOR_YR_MTH7", "Prior Year 1 Month 7", 8) // Opt
            , PRIOR_YR_MTH8 = Double("PRIOR_YR_MTH8", "Prior Year 1 Month 8", 8) // Opt
            , PRIOR_YR_MTH9 = Double("PRIOR_YR_MTH9", "Prior Year 1 Month 9", 8) // Opt
            , QUICK_RATIO_FLAG = SByte("QUICK_RATIO_FLAG", "Quick Ratio Account Flag", 1) // Opt
            ;

            public static Dict_ro<string, Sage_Field>
            Fields { get { return fields; } }

            static readonly Dict_ro<string, Sage_Field>
            fields = Make(ACCOUNT_REF
            , ACCOUNT_TYPE
            , AUDIT_REF
            , BALANCE
            , BALANCE_BF
            , BALANCE_FUTURE
            , BALANCE_MTH1
            , BALANCE_MTH10
            , BALANCE_MTH11
            , BALANCE_MTH12
            , BALANCE_MTH2
            , BALANCE_MTH3
            , BALANCE_MTH4
            , BALANCE_MTH5
            , BALANCE_MTH6
            , BALANCE_MTH7
            , BALANCE_MTH8
            , BALANCE_MTH9
            , BUDGET_MTH1
            , BUDGET_MTH10
            , BUDGET_MTH11
            , BUDGET_MTH12
            , BUDGET_MTH2
            , BUDGET_MTH3
            , BUDGET_MTH4
            , BUDGET_MTH5
            , BUDGET_MTH6
            , BUDGET_MTH7
            , BUDGET_MTH8
            , BUDGET_MTH9
            , CREDIT_BF
            , CREDIT_FUTURE
            , CREDIT_MTH1
            , CREDIT_MTH10
            , CREDIT_MTH11
            , CREDIT_MTH12
            , CREDIT_MTH2
            , CREDIT_MTH3
            , CREDIT_MTH4
            , CREDIT_MTH5
            , CREDIT_MTH6
            , CREDIT_MTH7
            , CREDIT_MTH8
            , CREDIT_MTH9
            , DEBIT_BF
            , DEBIT_FUTURE
            , DEBIT_MTH1
            , DEBIT_MTH10
            , DEBIT_MTH11
            , DEBIT_MTH12
            , DEBIT_MTH2
            , DEBIT_MTH3
            , DEBIT_MTH4
            , DEBIT_MTH5
            , DEBIT_MTH6
            , DEBIT_MTH7
            , DEBIT_MTH8
            , DEBIT_MTH9
            , DELETED_FLAG
            , EXTERNAL_USAGE
            , FIRST_SPLIT
            , LAST_SPLIT
            , NAME
            , NO_OF_SPLIT
            , PRIOR_YR2_MTH1
            , PRIOR_YR2_MTH10
            , PRIOR_YR2_MTH11
            , PRIOR_YR2_MTH12
            , PRIOR_YR2_MTH2
            , PRIOR_YR2_MTH3
            , PRIOR_YR2_MTH4
            , PRIOR_YR2_MTH5
            , PRIOR_YR2_MTH6
            , PRIOR_YR2_MTH7
            , PRIOR_YR2_MTH8
            , PRIOR_YR2_MTH9
            , PRIOR_YR3_MTH1
            , PRIOR_YR3_MTH10
            , PRIOR_YR3_MTH11
            , PRIOR_YR3_MTH12
            , PRIOR_YR3_MTH2
            , PRIOR_YR3_MTH3
            , PRIOR_YR3_MTH4
            , PRIOR_YR3_MTH5
            , PRIOR_YR3_MTH6
            , PRIOR_YR3_MTH7
            , PRIOR_YR3_MTH8
            , PRIOR_YR3_MTH9
            , PRIOR_YR4_MTH1
            , PRIOR_YR4_MTH10
            , PRIOR_YR4_MTH11
            , PRIOR_YR4_MTH12
            , PRIOR_YR4_MTH2
            , PRIOR_YR4_MTH3
            , PRIOR_YR4_MTH4
            , PRIOR_YR4_MTH5
            , PRIOR_YR4_MTH6
            , PRIOR_YR4_MTH7
            , PRIOR_YR4_MTH8
            , PRIOR_YR4_MTH9
            , PRIOR_YR5_MTH1
            , PRIOR_YR5_MTH10
            , PRIOR_YR5_MTH11
            , PRIOR_YR5_MTH12
            , PRIOR_YR5_MTH2
            , PRIOR_YR5_MTH3
            , PRIOR_YR5_MTH4
            , PRIOR_YR5_MTH5
            , PRIOR_YR5_MTH6
            , PRIOR_YR5_MTH7
            , PRIOR_YR5_MTH8
            , PRIOR_YR5_MTH9
            , PRIOR_YR_MTH1
            , PRIOR_YR_MTH10
            , PRIOR_YR_MTH11
            , PRIOR_YR_MTH12
            , PRIOR_YR_MTH2
            , PRIOR_YR_MTH3
            , PRIOR_YR_MTH4
            , PRIOR_YR_MTH5
            , PRIOR_YR_MTH6
            , PRIOR_YR_MTH7
            , PRIOR_YR_MTH8
            , PRIOR_YR_MTH9
            , QUICK_RATIO_FLAG
            );
        }
    }
}
