using System;
using System.Diagnostics;

using Versioning;


namespace Common
{
	
    // autogenerated: D:\Scripts\struct_creator2.pl
    [Serializable]
    [DebuggerStepThrough]
    public struct Sage_Invoice_Data
    {

        public Sage_Invoice_Data(
                    bool is_credit,
                    bool is_settled,

                    int number,
                    bool posted,
                    bool printed,
                    string taken_by,
                    decimal total_paid)
            : this() {

            this.Is_Credit_Note = is_credit;
            this.Is_Settled = is_settled;

            // (is_settled && !is_credit).tift();


            this.Number = number;
            this.Posted = posted;
            this.Printed = printed;
            this.Ours = false;
            this.Total_Paid = total_paid;
            this.Payment_Info = new Payment_Info(Payment_Type.Cash, total_paid);
            this.Taken_By = taken_by;
        }

        public Sage_Invoice_Data(
                    bool is_credit,
                    bool is_settled,

                    int number,
                    bool posted,
                    bool printed,
                    string taken_by,
                    Payment_Info payment_info)
            : this() {

            this.Is_Credit_Note = is_credit;
            this.Is_Settled = is_settled;


            this.Number = number;
            this.Posted = posted;
            this.Printed = printed;
            this.Ours = true;
            this.Total_Paid = payment_info.All_Paid;
            this.Payment_Info = payment_info;
            this.Taken_By = taken_by;

        }

        public bool Is_Credit_Note {
            get;
            set;
        }

        public bool Is_Settled {
            get;
            set;
        }


        public string Taken_By {
            get;
            set;
        }

        public int Number {
            get;
            set;
        }

        public bool Posted {
            get;
            set;
        }

        public bool Printed {
            get;
            set;
        }

        public bool Ours {
            get;
            set;
        }

        public decimal Total_Paid {
            get;
            set;
        }

        public Payment_Info Payment_Info {
            get;
            set;
        }





    }
}
