using System;

namespace Versioning
{
    public class Project : Sage_Object
    {
        /* Autogenerated by sage_wrapper_generator.pl */
        SageDataObject120.Project proj12;
        SageDataObject130.Project proj13;
        SageDataObject140.Project proj14;
        SageDataObject150.Project proj15;
        SageDataObject160.Project proj16;
        SageDataObject170.Project proj17;



        public Project(object inner, int version)
            : base(version) {
            this.Inner = inner;
            switch (m_version) {

                case 12: {
                        proj12 = (SageDataObject120.Project)inner;
                        return;
                    }

                case 13: {
                        proj13 = (SageDataObject130.Project)inner;
                        return;
                    }

                case 14: {
                        proj14 = (SageDataObject140.Project)inner;
                        return;
                    }

                case 15: {
                        proj15 = (SageDataObject150.Project)inner;
                        return;
                    }
                case 16: {
                        proj16 = (SageDataObject160.Project)inner;
                        return;
                    }
                case 17: {
                        proj17 = (SageDataObject170.Project)inner;
                        return;
                    }

                default: throw new InvalidOperationException("ver");
            }
        }
        /* Autogenerated with data_generator.pl */



        // temp2.pl

        public bool Delete() {
            switch (m_version) {
                case 12: return proj12.Delete();
                case 13: return proj13.Delete();
                case 14: return proj14.Delete();
                case 15: return proj15.Delete();
                case 16: return proj16.Delete();
                case 17: return proj17.Delete();
                default: throw new InvalidOperationException("ver");
            }
        }
        public bool Load(object index) {
            object temp = index;
            switch (m_version) {
                case 12: return proj12.Load(ref temp);
                case 13: return proj13.Load(ref temp);
                case 14: return proj14.Load(ref temp);
                case 15: return proj15.Load(ref temp);
                case 16: return proj16.Load(ref temp);
                case 17: return proj17.Load(ref temp);
                default: throw new InvalidOperationException("ver");
            }
        }
        public bool Update() {
            switch (m_version) {
                case 12: return proj12.Update();
                case 13: return proj13.Update();
                case 14: return proj14.Update();
                case 15: return proj15.Update();
                case 16: return proj16.Update();
                case 17: return proj17.Update();
                default: throw new InvalidOperationException("ver");
            }
        }

        public int ProjectID {
            get {
                switch (m_version) {
                    case 12: return proj12.ProjectID;
                    case 13: return proj13.ProjectID;
                    case 14: return proj14.ProjectID;
                    case 15: return proj15.ProjectID;
                    case 16: return proj16.ProjectID;
                    case 17: return proj17.ProjectID;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.ProjectID = value; return; }
                    case 13: { proj13.ProjectID = value; return; }
                    case 14: { proj14.ProjectID = value; return; }
                    case 15: { proj15.ProjectID = value; return; }
                    case 16: { proj16.ProjectID = value; return; }
                    case 17: { proj17.ProjectID = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public string Reference {
            get {
                switch (m_version) {
                    case 12: return proj12.Reference;
                    case 13: return proj13.Reference;
                    case 14: return proj14.Reference;
                    case 15: return proj15.Reference;
                    case 16: return proj16.Reference;
                    case 17: return proj17.Reference;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.Reference = value; return; }
                    case 13: { proj13.Reference = value; return; }
                    case 14: { proj14.Reference = value; return; }
                    case 15: { proj15.Reference = value; return; }
                    case 16: { proj16.Reference = value; return; }
                    case 17: { proj17.Reference = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }

        public string Address1 {
            get {
                switch (m_version) {
                    case 12: return proj12.Address1;
                    case 13: return proj13.Address1;
                    case 14: return proj14.Address1;
                    case 15: return proj15.Address1;
                    case 16: return proj16.Address1;
                    case 17: return proj17.Address1;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.Address1 = value; return; }
                    case 13: { proj13.Address1 = value; return; }
                    case 14: { proj14.Address1 = value; return; }
                    case 15: { proj15.Address1 = value; return; }
                    case 16: { proj16.Address1 = value; return; }
                    case 17: { proj17.Address1 = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public string Address2 {
            get {
                switch (m_version) {
                    case 12: return proj12.Address2;
                    case 13: return proj13.Address2;
                    case 14: return proj14.Address2;
                    case 15: return proj15.Address2;
                    case 16: return proj16.Address2;
                    case 17: return proj17.Address2;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.Address2 = value; return; }
                    case 13: { proj13.Address2 = value; return; }
                    case 14: { proj14.Address2 = value; return; }
                    case 15: { proj15.Address2 = value; return; }
                    case 16: { proj16.Address2 = value; return; }
                    case 17: { proj17.Address2 = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public string Address3 {
            get {
                switch (m_version) {
                    case 12: return proj12.Address3;
                    case 13: return proj13.Address3;
                    case 14: return proj14.Address3;
                    case 15: return proj15.Address3;
                    case 16: return proj16.Address3;
                    case 17: return proj17.Address3;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.Address3 = value; return; }
                    case 13: { proj13.Address3 = value; return; }
                    case 14: { proj14.Address3 = value; return; }
                    case 15: { proj15.Address3 = value; return; }
                    case 16: { proj16.Address3 = value; return; }
                    case 17: { proj17.Address3 = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public string Address4 {
            get {
                switch (m_version) {
                    case 12: return proj12.Address4;
                    case 13: return proj13.Address4;
                    case 14: return proj14.Address4;
                    case 15: return proj15.Address4;
                    case 16: return proj16.Address4;
                    case 17: return proj17.Address4;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.Address4 = value; return; }
                    case 13: { proj13.Address4 = value; return; }
                    case 14: { proj14.Address4 = value; return; }
                    case 15: { proj15.Address4 = value; return; }
                    case 16: { proj16.Address4 = value; return; }
                    case 17: { proj17.Address4 = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public string Address5 {
            get {
                switch (m_version) {
                    case 12: return proj12.Address5;
                    case 13: return proj13.Address5;
                    case 14: return proj14.Address5;
                    case 15: return proj15.Address5;
                    case 16: return proj16.Address5;
                    case 17: return proj17.Address5;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.Address5 = value; return; }
                    case 13: { proj13.Address5 = value; return; }
                    case 14: { proj14.Address5 = value; return; }
                    case 15: { proj15.Address5 = value; return; }
                    case 16: { proj16.Address5 = value; return; }
                    case 17: { proj17.Address5 = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public string Analysis1 {
            get {
                switch (m_version) {
                    case 12: return proj12.Analysis1;
                    case 13: return proj13.Analysis1;
                    case 14: return proj14.Analysis1;
                    case 15: return proj15.Analysis1;
                    case 16: return proj16.Analysis1;
                    case 17: return proj17.Analysis1;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.Analysis1 = value; return; }
                    case 13: { proj13.Analysis1 = value; return; }
                    case 14: { proj14.Analysis1 = value; return; }
                    case 15: { proj15.Analysis1 = value; return; }
                    case 16: { proj16.Analysis1 = value; return; }
                    case 17: { proj17.Analysis1 = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public string Analysis2 {
            get {
                switch (m_version) {
                    case 12: return proj12.Analysis2;
                    case 13: return proj13.Analysis2;
                    case 14: return proj14.Analysis2;
                    case 15: return proj15.Analysis2;
                    case 16: return proj16.Analysis2;
                    case 17: return proj17.Analysis2;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.Analysis2 = value; return; }
                    case 13: { proj13.Analysis2 = value; return; }
                    case 14: { proj14.Analysis2 = value; return; }
                    case 15: { proj15.Analysis2 = value; return; }
                    case 16: { proj16.Analysis2 = value; return; }
                    case 17: { proj17.Analysis2 = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public string Analysis3 {
            get {
                switch (m_version) {
                    case 12: return proj12.Analysis3;
                    case 13: return proj13.Analysis3;
                    case 14: return proj14.Analysis3;
                    case 15: return proj15.Analysis3;
                    case 16: return proj16.Analysis3;
                    case 17: return proj17.Analysis3;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.Analysis3 = value; return; }
                    case 13: { proj13.Analysis3 = value; return; }
                    case 14: { proj14.Analysis3 = value; return; }
                    case 15: { proj15.Analysis3 = value; return; }
                    case 16: { proj16.Analysis3 = value; return; }
                    case 17: { proj17.Analysis3 = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public double BilledNet {
            get {
                switch (m_version) {
                    case 12: return proj12.BilledNet;
                    case 13: return proj13.BilledNet;
                    case 14: return proj14.BilledNet;
                    case 15: return proj15.BilledNet;
                    case 16: return proj16.BilledNet;
                    case 17: return proj17.BilledNet;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.BilledNet = value; return; }
                    case 13: { proj13.BilledNet = value; return; }
                    case 14: { proj14.BilledNet = value; return; }
                    case 15: { proj15.BilledNet = value; return; }
                    case 16: { proj16.BilledNet = value; return; }
                    case 17: { proj17.BilledNet = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public double BilledVAT {
            get {
                switch (m_version) {
                    case 12: return proj12.BilledVAT;
                    case 13: return proj13.BilledVAT;
                    case 14: return proj14.BilledVAT;
                    case 15: return proj15.BilledVAT;
                    case 16: return proj16.BilledVAT;
                    case 17: return proj17.BilledVAT;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.BilledVAT = value; return; }
                    case 13: { proj13.BilledVAT = value; return; }
                    case 14: { proj14.BilledVAT = value; return; }
                    case 15: { proj15.BilledVAT = value; return; }
                    case 16: { proj16.BilledVAT = value; return; }
                    case 17: { proj17.BilledVAT = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public double CommittedCost {
            get {
                switch (m_version) {
                    //case 12: return proj12.CommittedCost;
                    //case 13: return proj13.CommittedCost;
                    //case 14: return proj14.CommittedCost;
                    //case 15: return proj15.CommittedCost;
                    case 16: return proj16.CommittedCost;
                    case 17: return proj17.CommittedCost;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    //case 12: { proj12.CommittedCost = value; return; }
                    //case 13: { proj13.CommittedCost = value; return; }
                    //case 14: { proj14.CommittedCost = value; return; }
                    //case 15: { proj15.CommittedCost = value; return; }
                    case 16: { proj16.CommittedCost = value; return; }
                    case 17: { proj17.CommittedCost = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }


        public string Contact {
            get {
                switch (m_version) {
                    case 12: return proj12.Contact;
                    case 13: return proj13.Contact;
                    case 14: return proj14.Contact;
                    case 15: return proj15.Contact;
                    case 16: return proj16.Contact;
                    case 17: return proj17.Contact;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.Contact = value; return; }
                    case 13: { proj13.Contact = value; return; }
                    case 14: { proj14.Contact = value; return; }
                    case 15: { proj15.Contact = value; return; }
                    case 16: { proj16.Contact = value; return; }
                    case 17: { proj17.Contact = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public object Country {
            get {
                switch (m_version) {
                    case 12: return proj12.Country;
                    case 13: return proj13.Country;
                    case 14: return proj14.Country;
                    case 15: return proj15.Country;
                    case 16: return proj16.Country;
                    case 17: return proj17.Country;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.Country = value; return; }
                    case 13: { proj13.Country = value; return; }
                    case 14: { proj14.Country = value; return; }
                    case 15: { proj15.Country = value; return; }
                    case 16: { proj16.Country = value; return; }
                    case 17: { proj17.Country = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public object Customer {
            get {
                switch (m_version) {
                    case 12: return proj12.Customer;
                    case 13: return proj13.Customer;
                    case 14: return proj14.Customer;
                    case 15: return proj15.Customer;
                    case 16: return proj16.Customer;
                    case 17: return proj17.Customer;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.Customer = value; return; }
                    case 13: { proj13.Customer = value; return; }
                    case 14: { proj14.Customer = value; return; }
                    case 15: { proj15.Customer = value; return; }
                    case 16: { proj16.Customer = value; return; }
                    case 17: { proj17.Customer = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public string Description {
            get {
                switch (m_version) {
                    case 12: return proj12.Description;
                    case 13: return proj13.Description;
                    case 14: return proj14.Description;
                    case 15: return proj15.Description;
                    case 16: return proj16.Description;
                    case 17: return proj17.Description;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.Description = value; return; }
                    case 13: { proj13.Description = value; return; }
                    case 14: { proj14.Description = value; return; }
                    case 15: { proj15.Description = value; return; }
                    case 16: { proj16.Description = value; return; }
                    case 17: { proj17.Description = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public string EMail {
            get {
                switch (m_version) {
                    case 12: return proj12.EMail;
                    case 13: return proj13.EMail;
                    case 14: return proj14.EMail;
                    case 15: return proj15.EMail;
                    case 16: return proj16.EMail;
                    case 17: return proj17.EMail;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.EMail = value; return; }
                    case 13: { proj13.EMail = value; return; }
                    case 14: { proj14.EMail = value; return; }
                    case 15: { proj15.EMail = value; return; }
                    case 16: { proj16.EMail = value; return; }
                    case 17: { proj17.EMail = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public DateTime EndDate {
            get {
                switch (m_version) {
                    case 12: return proj12.EndDate;
                    case 13: return proj13.EndDate;
                    case 14: return proj14.EndDate;
                    case 15: return proj15.EndDate;
                    case 16: return proj16.EndDate;
                    case 17: return proj17.EndDate;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.EndDate = value; return; }
                    case 13: { proj13.EndDate = value; return; }
                    case 14: { proj14.EndDate = value; return; }
                    case 15: { proj15.EndDate = value; return; }
                    case 16: { proj16.EndDate = value; return; }
                    case 17: { proj17.EndDate = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public string Fax {
            get {
                switch (m_version) {
                    case 12: return proj12.Fax;
                    case 13: return proj13.Fax;
                    case 14: return proj14.Fax;
                    case 15: return proj15.Fax;
                    case 16: return proj16.Fax;
                    case 17: return proj17.Fax;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.Fax = value; return; }
                    case 13: { proj13.Fax = value; return; }
                    case 14: { proj14.Fax = value; return; }
                    case 15: { proj15.Fax = value; return; }
                    case 16: { proj16.Fax = value; return; }
                    case 17: { proj17.Fax = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public DateTime LastBilledDate {
            get {
                switch (m_version) {
                    case 12: return proj12.LastBilledDate;
                    case 13: return proj13.LastBilledDate;
                    case 14: return proj14.LastBilledDate;
                    case 15: return proj15.LastBilledDate;
                    case 16: return proj16.LastBilledDate;
                    case 17: return proj17.LastBilledDate;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.LastBilledDate = value; return; }
                    case 13: { proj13.LastBilledDate = value; return; }
                    case 14: { proj14.LastBilledDate = value; return; }
                    case 15: { proj15.LastBilledDate = value; return; }
                    case 16: { proj16.LastBilledDate = value; return; }
                    case 17: { proj17.LastBilledDate = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public DateTime LastCostDate {
            get {
                switch (m_version) {
                    case 12: return proj12.LastCostDate;
                    case 13: return proj13.LastCostDate;
                    case 14: return proj14.LastCostDate;
                    case 15: return proj15.LastCostDate;
                    case 16: return proj16.LastCostDate;
                    case 17: return proj17.LastCostDate;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.LastCostDate = value; return; }
                    case 13: { proj13.LastCostDate = value; return; }
                    case 14: { proj14.LastCostDate = value; return; }
                    case 15: { proj15.LastCostDate = value; return; }
                    case 16: { proj16.LastCostDate = value; return; }
                    case 17: { proj17.LastCostDate = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public string Name {
            get {
                switch (m_version) {
                    case 12: return proj12.Name;
                    case 13: return proj13.Name;
                    case 14: return proj14.Name;
                    case 15: return proj15.Name;
                    case 16: return proj16.Name;
                    case 17: return proj17.Name;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.Name = value; return; }
                    case 13: { proj13.Name = value; return; }
                    case 14: { proj14.Name = value; return; }
                    case 15: { proj15.Name = value; return; }
                    case 16: { proj16.Name = value; return; }
                    case 17: { proj17.Name = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public string OrderNumber {
            get {
                switch (m_version) {
                    case 12: return proj12.OrderNumber;
                    case 13: return proj13.OrderNumber;
                    case 14: return proj14.OrderNumber;
                    case 15: return proj15.OrderNumber;
                    case 16: return proj16.OrderNumber;
                    case 17: return proj17.OrderNumber;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.OrderNumber = value; return; }
                    case 13: { proj13.OrderNumber = value; return; }
                    case 14: { proj14.OrderNumber = value; return; }
                    case 15: { proj15.OrderNumber = value; return; }
                    case 16: { proj16.OrderNumber = value; return; }
                    case 17: { proj17.OrderNumber = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public double OutstandingToBill {
            get {
                switch (m_version) {
                    case 12: return proj12.OutstandingToBill;
                    case 13: return proj13.OutstandingToBill;
                    case 14: return proj14.OutstandingToBill;
                    case 15: return proj15.OutstandingToBill;
                    case 16: return proj16.OutstandingToBill;
                    case 17: return proj17.OutstandingToBill;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.OutstandingToBill = value; return; }
                    case 13: { proj13.OutstandingToBill = value; return; }
                    case 14: { proj14.OutstandingToBill = value; return; }
                    case 15: { proj15.OutstandingToBill = value; return; }
                    case 16: { proj16.OutstandingToBill = value; return; }
                    case 17: { proj17.OutstandingToBill = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public double PriceQuoted {
            get {
                switch (m_version) {
                    case 12: return proj12.PriceQuoted;
                    case 13: return proj13.PriceQuoted;
                    case 14: return proj14.PriceQuoted;
                    case 15: return proj15.PriceQuoted;
                    case 16: return proj16.PriceQuoted;
                    case 17: return proj17.PriceQuoted;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.PriceQuoted = value; return; }
                    case 13: { proj13.PriceQuoted = value; return; }
                    case 14: { proj14.PriceQuoted = value; return; }
                    case 15: { proj15.PriceQuoted = value; return; }
                    case 16: { proj16.PriceQuoted = value; return; }
                    case 17: { proj17.PriceQuoted = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public double ProfitToDate {
            get {
                switch (m_version) {
                    case 12: return proj12.ProfitToDate;
                    case 13: return proj13.ProfitToDate;
                    case 14: return proj14.ProfitToDate;
                    case 15: return proj15.ProfitToDate;
                    case 16: return proj16.ProfitToDate;
                    case 17: return proj17.ProfitToDate;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.ProfitToDate = value; return; }
                    case 13: { proj13.ProfitToDate = value; return; }
                    case 14: { proj14.ProfitToDate = value; return; }
                    case 15: { proj15.ProfitToDate = value; return; }
                    case 16: { proj16.ProfitToDate = value; return; }
                    case 17: { proj17.ProfitToDate = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }

        public DateTime StartDate {
            get {
                switch (m_version) {
                    case 12: return proj12.StartDate;
                    case 13: return proj13.StartDate;
                    case 14: return proj14.StartDate;
                    case 15: return proj15.StartDate;
                    case 16: return proj16.StartDate;
                    case 17: return proj17.StartDate;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.StartDate = value; return; }
                    case 13: { proj13.StartDate = value; return; }
                    case 14: { proj14.StartDate = value; return; }
                    case 15: { proj15.StartDate = value; return; }
                    case 16: { proj16.StartDate = value; return; }
                    case 17: { proj17.StartDate = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public object Status {
            get {
                switch (m_version) {
                    case 12: return proj12.Status;
                    case 13: return proj13.Status;
                    case 14: return proj14.Status;
                    case 15: return proj15.Status;
                    case 16: return proj16.Status;
                    case 17: return proj17.Status;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.Status = value; return; }
                    case 13: { proj13.Status = value; return; }
                    case 14: { proj14.Status = value; return; }
                    case 15: { proj15.Status = value; return; }
                    case 16: { proj16.Status = value; return; }
                    case 17: { proj17.Status = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public string Telehpone {
            get {
                switch (m_version) {
                    case 12: return proj12.Telehpone;
                    case 13: return proj13.Telehpone;
                    case 14: return proj14.Telehpone;
                    case 15: return proj15.Telehpone;
                    case 16: return proj16.Telehpone;
                    case 17: return proj17.Telehpone;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.Telehpone = value; return; }
                    case 13: { proj13.Telehpone = value; return; }
                    case 14: { proj14.Telehpone = value; return; }
                    case 15: { proj15.Telehpone = value; return; }
                    case 16: { proj16.Telehpone = value; return; }
                    case 17: { proj17.Telehpone = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public double TotalBilled {
            get {
                switch (m_version) {
                    case 12: return proj12.TotalBilled;
                    case 13: return proj13.TotalBilled;
                    case 14: return proj14.TotalBilled;
                    case 15: return proj15.TotalBilled;
                    case 16: return proj16.TotalBilled;
                    case 17: return proj17.TotalBilled;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.TotalBilled = value; return; }
                    case 13: { proj13.TotalBilled = value; return; }
                    case 14: { proj14.TotalBilled = value; return; }
                    case 15: { proj15.TotalBilled = value; return; }
                    case 16: { proj16.TotalBilled = value; return; }
                    case 17: { proj17.TotalBilled = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public double TotalBudget {
            get {
                switch (m_version) {
                    case 12: return proj12.TotalBudget;
                    case 13: return proj13.TotalBudget;
                    case 14: return proj14.TotalBudget;
                    case 15: return proj15.TotalBudget;
                    case 16: return proj16.TotalBudget;
                    case 17: return proj17.TotalBudget;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.TotalBudget = value; return; }
                    case 13: { proj13.TotalBudget = value; return; }
                    case 14: { proj14.TotalBudget = value; return; }
                    case 15: { proj15.TotalBudget = value; return; }
                    case 16: { proj16.TotalBudget = value; return; }
                    case 17: { proj17.TotalBudget = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public double TotalCost {
            get {
                switch (m_version) {
                    case 12: return proj12.TotalCost;
                    case 13: return proj13.TotalCost;
                    case 14: return proj14.TotalCost;
                    case 15: return proj15.TotalCost;
                    case 16: return proj16.TotalCost;
                    case 17: return proj17.TotalCost;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.TotalCost = value; return; }
                    case 13: { proj13.TotalCost = value; return; }
                    case 14: { proj14.TotalCost = value; return; }
                    case 15: { proj15.TotalCost = value; return; }
                    case 16: { proj16.TotalCost = value; return; }
                    case 17: { proj17.TotalCost = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public object Transactions {
            get {
                switch (m_version) {
                    case 12: return proj12.Transactions;
                    case 13: return proj13.Transactions;
                    case 14: return proj14.Transactions;
                    case 15: return proj15.Transactions;
                    case 16: return proj16.Transactions;
                    case 17: return proj17.Transactions;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.Transactions = value; return; }
                    case 13: { proj13.Transactions = value; return; }
                    case 14: { proj14.Transactions = value; return; }
                    case 15: { proj15.Transactions = value; return; }
                    case 16: { proj16.Transactions = value; return; }
                    case 17: { proj17.Transactions = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }
        public double Variance {
            get {
                switch (m_version) {
                    case 12: return proj12.Variance;
                    case 13: return proj13.Variance;
                    case 14: return proj14.Variance;
                    case 15: return proj15.Variance;
                    case 16: return proj16.Variance;
                    case 17: return proj17.Variance;
                    default: throw new InvalidOperationException("ver");
                }
            }
            set {
                switch (m_version) {
                    case 12: { proj12.Variance = value; return; }
                    case 13: { proj13.Variance = value; return; }
                    case 14: { proj14.Variance = value; return; }
                    case 15: { proj15.Variance = value; return; }
                    case 16: { proj16.Variance = value; return; }
                    case 17: { proj17.Variance = value; return; }
                    default: throw new InvalidOperationException("ver");

                }
            }

        }


        public object Inner {
            get;
            private set;
        }


    }
}